import Head from 'next/head';
// import styles from '../styles/Home.module.css';
import styles from './navbar.module.css'

export default function navBar() {
    const handleClick = () => {
        // console.log(styles.menu);
        let overlay = document.querySelector(`.${styles.navBarOverlay}`);
        let hide = styles.hide;
        overlay.classList.toggle(hide);
        let icon = document.querySelector('.icon');
        icon.classList.toggle('fa-bars');
        icon.classList.toggle('fa-xmark');
        // console.log(icon.classList);
        // console.log(overlay.classList);
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link> */}
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
            </Head>

            <main>
                <section className={styles.navPrimary}>
                    <nav className={styles.navContainer}>

                        <a className={styles.logo} href="/"><i className="fa-solid fa-infinity fa-2xl"></i><span className={styles.logoTxt}>Projects</span></a>
                        <div className={`${styles.spacing}`}></div>
                        <div className={styles.itemsContainer}>
                            <ul className={styles.navUL}>
                                <li className={`${styles.navItems} ${styles.portfolio}`}>
                                    <a className={styles.navLink1} data-content="Visit My Website" href="https://alec74.github.io/AlecMcGlone/" target="_blank"><i className="fa-solid fa-square-arrow-up-right fa-xl"></i></a>
                                </li>
                                <li className={`${styles.navItems} ${styles.themeToggle}`}>
                                    <a className={styles.navLink1} data-content="Toggle Light/Dark Mode" href="#"><i className="fa-solid fa-moon fa-xl"></i></a>
                                </li>
                                <li className={`${styles.navItems} ${styles.cart}`}>
                                    <a className={styles.navLink1} data-content="View Cart" href="#"><i className="fa-solid fa-cart-shopping"></i></a>
                                </li>
                                <li className={styles.navItems}>
                                    <a onClick={() => handleClick()} className={`${styles.navLink} ${styles.menu}`} href="#"><i className="icon fa-solid fa-bars fa-2xl"></i></a>
                                </li>
                            </ul>
                        </div>

                    </nav>
                </section>
                {/* <a className={styles.navLink1} data-content="Toggle Light/Dark Mode" href="#"><i className="fa-solid fa-moon fa-xl"></i></a> */}
                <section className={`${styles.navBarOverlay} ${styles.hide}`}>
                    <div className={`${styles.grid}`}>
                        <a href="https://alec74.github.io/AlecMcGlone/" target="_blank"><div className={`${styles.gridItem}`}><i className="fa-solid fa-cart-shopping"></i><h3>View Cart</h3></div></a>
                        <a href='#'><div className={`${styles.gridItem}`}><i className="fa-solid fa-moon fa-xl"></i><h3>Toggle Light/Dark Mode</h3></div></a>
                        <a href='#'><div className={`${styles.gridItem}`}><i className="fa-solid fa-square-arrow-up-right fa-xl"></i><h3>Visit My Website</h3></div></a>
                    </div>
                </section>
            </main>
            {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossOrigin="anonymous"></script> */}
        </div>
    )
}